version: 2.1
orbs:
  node: circleci/node@7.2.1
  aws-s3: circleci/aws-s3@4.1.3
  aws-cli: circleci/aws-cli@5.1.1

jobs:
  build-react-app:
    executor:
      name: node/default
      resource_class: medium
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-npm-deps-{{ checksum "package-lock.json" }}
            - v1-npm-deps-
      - node/install-packages:
          pkg-manager: npm
          cache-path: ~/.npm
          override-ci-command: npm ci --prefer-offline
      - save_cache:
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
      - restore_cache:
          keys:
            - v1-build-cache-{{ .Branch }}-{{ .Revision }}
            - v1-build-cache-{{ .Branch }}-
            - v1-build-cache-
      - run:
          command: npm run build
          name: Build React app
      - save_cache:
          key: v1-build-cache-{{ .Branch }}-{{ .Revision }}
          paths:
            - dist
            - node_modules/.vite
      - run:
          name: Create tarball
          command: tar -czf app-${CIRCLE_SHA1}.tar.gz -C dist .
      - persist_to_workspace:
          root: .
          paths:
            - app-*.tar.gz

  deploy-artifact:
    executor:
      name: aws-s3/default
      resource_class: small
    steps:
      - attach_workspace:
          at: .
      - aws-cli/setup:
          role_arn: ${AWS_ROLE_ARN}
          region: ${AWS_REGION}
      - run:
          name: Plan deployment
          command: |
            circleci run release plan "${CIRCLE_JOB}" \
              --environment-name="default" \
              --component-name="${CIRCLE_PROJECT_REPONAME}" \
              --target-version="1.0.${CIRCLE_BUILD_NUM}-${CIRCLE_SHA1}"
      - aws-s3/copy:
          from: app-${CIRCLE_SHA1}.tar.gz
          to: 's3://${AWS_S3_BUCKET}/artifacts/app-${CIRCLE_SHA1}.tar.gz'
          arguments: '--acl private --storage-class INTELLIGENT_TIERING'
      - run:
          name: Update deployment status to running
          command: circleci run release update "${CIRCLE_JOB}" --status=RUNNING
      - run:
          name: Update deployment status to success
          command: circleci run release update "${CIRCLE_JOB}" --status=SUCCESS
          when: on_success
      - run:
          name: Update deployment status to failed
          command: circleci run release update "${CIRCLE_JOB}" --status=FAILED
          when: on_fail


workflows:
  build-react-app:
    jobs:
      - build-react-app
      - deploy-artifact:
          context: aws-oidc
          requires:
            - build-react-app
          filters:
            branches:
              only:
                - main