version: 2.1
orbs:
  node: circleci/node@7.2.1
  aws-s3: circleci/aws-s3@4.1.3
  aws-cli: circleci/aws-cli@5.1.1

jobs:
  test:
    executor:
      name: node/default
      resource_class: small
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run test:run
          name: Run tests
      - run:
          command: npm run test:coverage
          name: Generate coverage report
      - store_test_results:
          path: ./coverage
      - store_artifacts:
          path: ./coverage
          destination: coverage

  build-react-app:
    executor:
      name: node/default
      resource_class: small
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run build
          name: Build React app
      
      # tar.gz に圧縮
      - run:
          name: Create tarball
          command: |
            cd dist
            tar -czf ../app-${CIRCLE_SHA1}.tar.gz .
            cd ..
      - persist_to_workspace:
          root: .
          paths:
            - app-*.tar.gz

  deploy-artifact:
    executor:
      name: aws-s3/default
      resource_class: small
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Plan deployment
          command: |
            circleci run release plan "${CIRCLE_JOB}" \
              --environment-name="default" \
              --component-name="${CIRCLE_PROJECT_REPONAME}" \
              --target-version="1.0.${CIRCLE_BUILD_NUM}-${CIRCLE_SHA1}"
      - aws-cli/setup:
          role_arn: ${AWS_ROLE_ARN}
          region: ${AWS_REGION}
      - aws-s3/copy:
          from: app-${CIRCLE_SHA1}.tar.gz
          to: 's3://${AWS_S3_BUCKET}/artifacts/app-${CIRCLE_SHA1}.tar.gz'
          arguments: '--acl private'
      - run:
          name: Update deployment status to running
          command: circleci run release update "${CIRCLE_JOB}" --status=RUNNING
      - run:
          name: Update deployment status to success
          command: circleci run release update "${CIRCLE_JOB}" --status=SUCCESS
          when: on_success
      - run:
          name: Update deployment status to failed
          command: circleci run release update "${CIRCLE_JOB}" --status=FAILED
          when: on_fail


workflows:
  build-react-app:
    jobs:
      - test
      - build-react-app:
          requires:
            - test
      - deploy-artifact:
          context: aws-oidc
          requires:
            - build-react-app
          filters:
            branches:
              only:
                - main